apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s/platform-postgres-depl.yaml
      - ./k8s/platform-depl.yaml
      - ./k8s/client-depl.yaml
      - ./k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: anfelo/chillhacks_client
      context: ../client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
          - src: "**/*.vue"
            dest: .
    - image: anfelo/chillhacks_platform
      context: ../platform
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.go"
            dest: .
